spring.application.name=S-D

spring.data.mongodb.uri=${MONGO_URL}

server.address=0.0.0.0
server.port=${PORT:8080}


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=TON_LOGIN_BREVO
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.mail.host=smtp.gmail.com
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
#spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true

spring.main.lazy-initialization=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=40MB

stripe.secret.key=${STRIPE_SECRET_KEY}
